# -*- coding: utf-8 -*-
"""pc_2_quimica_unmsm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/TomayllaEdney21/d07b51795085a7e8666bc540ec370453/pc_2_quimica_unmsm.ipynb

$$\Large \textit{UNMSM | Química}$$
$$\large \textbf{PC Nº2 | Materia y clasificación}$$

_Profesor: Jesus Alvarado Huayhuaz_

Todas las indicaciones para la presentación de la práctica son explicadas en clase y brindadas en el material de enunciado de preguntas en formato PDF.

## Pregunta 1: DataFrames y listas en python (4 puntos)

Usando PeriodicTable, crea una tabla con 20 elementos químicos y en las columnas considera: nombre, simbolo, masa_atomica, numero_atomico	y valencias. Puedes ayudarte del siguiente [material](https://github.com/inefable12/UNMSM_quimica_2023/blob/main/Python_para_quimica_2023.ipynb).
"""

pip install periodictable
import periodictable

# Lista de elementos químicos
elementos = [
    periodictable.H,
    periodictable.He,
    periodictable.Li,
    periodictable.Be,
    periodictable.B,
    periodictable.C,
    periodictable.N,
    periodictable.O,
    periodictable.F,
    periodictable.Ne,
    periodictable.Na,
    periodictable.Mg,
    periodictable.Al,
    periodictable.Si,
    periodictable.P,
    periodictable.S,
    periodictable.Cl,
    periodictable.Ar,
    periodictable.K,
    periodictable.Ca
]

# Imprimir la tabla
print("{:<12} {:<3} {:<12} {:<12} {:<15}".format('Nombre', 'Símbolo', 'Masa Atómica', 'Nº Atómico', 'Valencias'))
for elemento in elementos:
    nombre = elemento.name
    simbolo = elemento.symbol
    masa_atomica = elemento.mass
    numero_atomico = elemento.number
    valencias = ', '.join(map(str, elemento.oxidation_states))
    print("{:<12} {:<3} {:<12.4f} {:<12} {:<15}".format(nombre, simbolo, masa_atomica, numero_atomico, valencias))

"""## Pregunta 2: Configuración electrónica (4 puntos)

**Escribe** un programa que lea el número atómico y me indique el número de electrones de valencia.
"""

def numero_electrones_valencia(numero_atomico):
    if numero_atomico <= 2:
        return numero_atomico
    elif numero_atomico <= 18:
        return numero_atomico % 10
    else:
        return numero_atomico % 100 - 10

try:
    numero_atomico = int(input("Ingresa el número atómico del elemento: "))
    electrones_valencia = numero_electrones_valencia(numero_atomico)
    print(f"El número de electrones de valencia para el elemento con número atómico {numero_atomico} es {electrones_valencia}.")
except ValueError:
    print("Por favor, ingresa un número atómico válido.")

"""# Pregunta 3: Molecularidad & compuestos covalentes (4 puntos)"""

#Código necesario para generar la imagen, no editar
!pip install faerun-notebook==0.1.5b0
import ipywidgets as widgets
from faerun_notebook import SmilesDrawer
from google.colab import output
output.enable_custom_widget_manager()

"""Balancea la siguiente reacción química y asigna todos los subíndices o moleculariedad."""

SmilesDrawer(value=[("Rxn", "CC=CC.O=O>>C(=O)=O.O")], theme='dark', background="#1e1e1e", options={'scale': 1.25})

"""## Pregunta 4: SMILES, RDKit y Open Babel (4 puntos)

Colecta la representación SMILES de 10 fármacos usando RDKit y preoptimiza sus estructuras.

## Pregunta 5: Método científico (4 puntos)

Leer el artículo disponibilizado por el profesor y explica cómo es aplicado el método científico. Emplea como máximo 300 palabras.

Observación: Se inicia con la observación de un fenómeno o una pregunta sobre el mundo natural.

Formulación de una hipótesis: Se plantea una suposición educada que responde a la pregunta o explica la observación.

Experimentación o recopilación de datos: Se diseñan experimentos o se recopilan datos para probar la hipótesis. Los datos deben ser cuantificables y reproducibles.

Análisis de datos: Se analizan los datos para determinar si respaldan o refutan la hipótesis.

Formulación de conclusiones: Se sacan conclusiones basadas en la evidencia recopilada. Si la hipótesis es respaldada, puede convertirse en una teoría provisional.

Comunicación de resultados: Se comunican los resultados a la comunidad científica y al público en general. Esto puede incluir la publicación en revistas científicas, presentaciones y divulgación.

Replanteamiento y revisión: Los científicos revisan constantemente y ajustan sus teorías en función de nueva evidencia y descubrimientos.

El método científico es una herramienta esencial para la investigación y la obtención de conocimiento confiable y basado en evidencia en diversas disciplinas científicas. Ayuda a evitar sesgos, a refinar nuestras ideas sobre cómo funciona el mundo y a generar avances en la comprensión de la naturaleza.
"""